name: Go

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.22'

    - name: Check out code
      uses: actions/checkout@v4

    - name: Run tests
      run: go test ./...
